### ISSUE TITLE
HTML5: WebSocket disconnection causes "unsupported socketcall syscall 13"

### ISSUE THREAD

**Issue by endel** [britzl/defold-websocket#7]
Related: https://forum.defold.com/t/using-websocket-getting-multiple-errors/23356/11?u=endel

```
abort("unsupported socketcall syscall 13") at Error
    at jsStackTrace (http://localhost:65378/html5/Game.js:1:21724)
    at stackTrace (http://localhost:65378/html5/Game.js:1:21907)
    at abort (http://localhost:65378/html5/Game.js:24:17388)
    at ___syscall102 (http://localhost:65378/html5/Game.js:1:1812877)
    at oGa (http://localhost:65378/html5/Game.js:13:301820)
    at b3 (http://localhost:65378/html5/Game.js:6:326220)
    at s2 (http://localhost:65378/html5/Game.js:6:319580)
    at o6 (http://localhost:65378/html5/Game.js:11:33829)
    at j8 (http://localhost:65378/html5/Game.js:11:140848)
    at v6 (http://localhost:65378/html5/Game.js:11:40208)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

**Comment by endel** [comment]
Thanks a lot @britzl <3 <3 <3
